// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportStats.Data;

#nullable disable

namespace SportStats.Migrations
{
    [DbContext(typeof(SportStatsContext))]
    [Migration("20220605220708_Migratia2")]
    partial class Migratia2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SportStats.Models.Akhmat", b =>
                {
                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Guest_Goals")
                        .HasColumnType("int");

                    b.Property<int>("Guest_Win")
                        .HasColumnType("int");

                    b.Property<string>("Head_Coach")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Home_Goals")
                        .HasColumnType("int");

                    b.Property<int>("Home_Win")
                        .HasColumnType("int");

                    b.Property<int>("Red_Cards")
                        .HasColumnType("int");

                    b.Property<string>("Stadium")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YellowDisruptionOfTheAttack")
                        .HasColumnType("int");

                    b.Property<int>("YellowRoughPlay")
                        .HasColumnType("int");

                    b.Property<int>("YellowUnsportsmanlikeBehavior")
                        .HasColumnType("int");

                    b.Property<int>("Yellow_Cards")
                        .HasColumnType("int");

                    b.Property<int>("Yellow_Other")
                        .HasColumnType("int");

                    b.HasKey("Title");

                    b.ToTable("Akhmat");
                });

            modelBuilder.Entity("SportStats.Models.Arsenal", b =>
                {
                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Guest_Goals")
                        .HasColumnType("int");

                    b.Property<int>("Guest_Win")
                        .HasColumnType("int");

                    b.Property<string>("Head_Coach")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Home_Goals")
                        .HasColumnType("int");

                    b.Property<int>("Home_Win")
                        .HasColumnType("int");

                    b.Property<int>("Red_Cards")
                        .HasColumnType("int");

                    b.Property<string>("Stadium")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YellowDisruptionOfTheAttack")
                        .HasColumnType("int");

                    b.Property<int>("YellowRoughPlay")
                        .HasColumnType("int");

                    b.Property<int>("YellowUnsportsmanlikeBehavior")
                        .HasColumnType("int");

                    b.Property<int>("Yellow_Cards")
                        .HasColumnType("int");

                    b.Property<int>("Yellow_Other")
                        .HasColumnType("int");

                    b.HasKey("Title");

                    b.ToTable("Arsenal");
                });

            modelBuilder.Entity("SportStats.Models.CSKA", b =>
                {
                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Guest_Goals")
                        .HasColumnType("int");

                    b.Property<int>("Guest_Win")
                        .HasColumnType("int");

                    b.Property<string>("Head_Coach")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Home_Goals")
                        .HasColumnType("int");

                    b.Property<int>("Home_Win")
                        .HasColumnType("int");

                    b.Property<int>("Red_Cards")
                        .HasColumnType("int");

                    b.Property<string>("Stadium")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YellowDisruptionOfTheAttack")
                        .HasColumnType("int");

                    b.Property<int>("YellowRoughPlay")
                        .HasColumnType("int");

                    b.Property<int>("YellowUnsportsmanlikeBehavior")
                        .HasColumnType("int");

                    b.Property<int>("Yellow_Cards")
                        .HasColumnType("int");

                    b.Property<int>("Yellow_Other")
                        .HasColumnType("int");

                    b.HasKey("Title");

                    b.ToTable("CSKA");
                });

            modelBuilder.Entity("SportStats.Models.Dynamo", b =>
                {
                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Guest_Goals")
                        .HasColumnType("int");

                    b.Property<int>("Guest_Win")
                        .HasColumnType("int");

                    b.Property<string>("Head_Coach")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Home_Goals")
                        .HasColumnType("int");

                    b.Property<int>("Home_Win")
                        .HasColumnType("int");

                    b.Property<int>("Red_Cards")
                        .HasColumnType("int");

                    b.Property<string>("Stadium")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YellowDisruptionOfTheAttack")
                        .HasColumnType("int");

                    b.Property<int>("YellowRoughPlay")
                        .HasColumnType("int");

                    b.Property<int>("YellowUnsportsmanlikeBehavior")
                        .HasColumnType("int");

                    b.Property<int>("Yellow_Cards")
                        .HasColumnType("int");

                    b.Property<int>("Yellow_Other")
                        .HasColumnType("int");

                    b.HasKey("Title");

                    b.ToTable("Dynamo");
                });

            modelBuilder.Entity("SportStats.Models.Khimki", b =>
                {
                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Guest_Goals")
                        .HasColumnType("int");

                    b.Property<int>("Guest_Win")
                        .HasColumnType("int");

                    b.Property<string>("Head_Coach")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Home_Goals")
                        .HasColumnType("int");

                    b.Property<int>("Home_Win")
                        .HasColumnType("int");

                    b.Property<int>("Red_Cards")
                        .HasColumnType("int");

                    b.Property<string>("Stadium")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YellowDisruptionOfTheAttack")
                        .HasColumnType("int");

                    b.Property<int>("YellowRoughPlay")
                        .HasColumnType("int");

                    b.Property<int>("YellowUnsportsmanlikeBehavior")
                        .HasColumnType("int");

                    b.Property<int>("Yellow_Cards")
                        .HasColumnType("int");

                    b.Property<int>("Yellow_Other")
                        .HasColumnType("int");

                    b.HasKey("Title");

                    b.ToTable("Khimki");
                });

            modelBuilder.Entity("SportStats.Models.Krasnodar", b =>
                {
                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Guest_Goals")
                        .HasColumnType("int");

                    b.Property<int>("Guest_Win")
                        .HasColumnType("int");

                    b.Property<string>("Head_Coach")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Home_Goals")
                        .HasColumnType("int");

                    b.Property<int>("Home_Win")
                        .HasColumnType("int");

                    b.Property<int>("Red_Cards")
                        .HasColumnType("int");

                    b.Property<string>("Stadium")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YellowDisruptionOfTheAttack")
                        .HasColumnType("int");

                    b.Property<int>("YellowRoughPlay")
                        .HasColumnType("int");

                    b.Property<int>("YellowUnsportsmanlikeBehavior")
                        .HasColumnType("int");

                    b.Property<int>("Yellow_Cards")
                        .HasColumnType("int");

                    b.Property<int>("Yellow_Other")
                        .HasColumnType("int");

                    b.HasKey("Title");

                    b.ToTable("Krasnodar");
                });

            modelBuilder.Entity("SportStats.Models.KrylyaSovetov", b =>
                {
                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Guest_Goals")
                        .HasColumnType("int");

                    b.Property<int>("Guest_Win")
                        .HasColumnType("int");

                    b.Property<string>("Head_Coach")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Home_Goals")
                        .HasColumnType("int");

                    b.Property<int>("Home_Win")
                        .HasColumnType("int");

                    b.Property<int>("Red_Cards")
                        .HasColumnType("int");

                    b.Property<string>("Stadium")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YellowDisruptionOfTheAttack")
                        .HasColumnType("int");

                    b.Property<int>("YellowRoughPlay")
                        .HasColumnType("int");

                    b.Property<int>("YellowUnsportsmanlikeBehavior")
                        .HasColumnType("int");

                    b.Property<int>("Yellow_Cards")
                        .HasColumnType("int");

                    b.Property<int>("Yellow_Other")
                        .HasColumnType("int");

                    b.HasKey("Title");

                    b.ToTable("KrylyaSovetov");
                });

            modelBuilder.Entity("SportStats.Models.Lokomotiv", b =>
                {
                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Guest_Goals")
                        .HasColumnType("int");

                    b.Property<int>("Guest_Win")
                        .HasColumnType("int");

                    b.Property<string>("Head_Coach")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Home_Goals")
                        .HasColumnType("int");

                    b.Property<int>("Home_Win")
                        .HasColumnType("int");

                    b.Property<int>("Red_Cards")
                        .HasColumnType("int");

                    b.Property<string>("Stadium")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YellowDisruptionOfTheAttack")
                        .HasColumnType("int");

                    b.Property<int>("YellowRoughPlay")
                        .HasColumnType("int");

                    b.Property<int>("YellowUnsportsmanlikeBehavior")
                        .HasColumnType("int");

                    b.Property<int>("Yellow_Cards")
                        .HasColumnType("int");

                    b.Property<int>("Yellow_Other")
                        .HasColumnType("int");

                    b.HasKey("Title");

                    b.ToTable("Lokomotiv");
                });

            modelBuilder.Entity("SportStats.Models.NizhniyNovgorod", b =>
                {
                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Guest_Goals")
                        .HasColumnType("int");

                    b.Property<int>("Guest_Win")
                        .HasColumnType("int");

                    b.Property<string>("Head_Coach")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Home_Goals")
                        .HasColumnType("int");

                    b.Property<int>("Home_Win")
                        .HasColumnType("int");

                    b.Property<int>("Red_Cards")
                        .HasColumnType("int");

                    b.Property<string>("Stadium")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YellowDisruptionOfTheAttack")
                        .HasColumnType("int");

                    b.Property<int>("YellowRoughPlay")
                        .HasColumnType("int");

                    b.Property<int>("YellowUnsportsmanlikeBehavior")
                        .HasColumnType("int");

                    b.Property<int>("Yellow_Cards")
                        .HasColumnType("int");

                    b.Property<int>("Yellow_Other")
                        .HasColumnType("int");

                    b.HasKey("Title");

                    b.ToTable("NizhniyNovgorod");
                });

            modelBuilder.Entity("SportStats.Models.Rostov", b =>
                {
                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Guest_Goals")
                        .HasColumnType("int");

                    b.Property<int>("Guest_Win")
                        .HasColumnType("int");

                    b.Property<string>("Head_Coach")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Home_Goals")
                        .HasColumnType("int");

                    b.Property<int>("Home_Win")
                        .HasColumnType("int");

                    b.Property<int>("Red_Cards")
                        .HasColumnType("int");

                    b.Property<string>("Stadium")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YellowDisruptionOfTheAttack")
                        .HasColumnType("int");

                    b.Property<int>("YellowRoughPlay")
                        .HasColumnType("int");

                    b.Property<int>("YellowUnsportsmanlikeBehavior")
                        .HasColumnType("int");

                    b.Property<int>("Yellow_Cards")
                        .HasColumnType("int");

                    b.Property<int>("Yellow_Other")
                        .HasColumnType("int");

                    b.HasKey("Title");

                    b.ToTable("Rostov");
                });

            modelBuilder.Entity("SportStats.Models.Rubin", b =>
                {
                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Guest_Goals")
                        .HasColumnType("int");

                    b.Property<int>("Guest_Win")
                        .HasColumnType("int");

                    b.Property<string>("Head_Coach")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Home_Goals")
                        .HasColumnType("int");

                    b.Property<int>("Home_Win")
                        .HasColumnType("int");

                    b.Property<int>("Red_Cards")
                        .HasColumnType("int");

                    b.Property<string>("Stadium")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YellowDisruptionOfTheAttack")
                        .HasColumnType("int");

                    b.Property<int>("YellowRoughPlay")
                        .HasColumnType("int");

                    b.Property<int>("YellowUnsportsmanlikeBehavior")
                        .HasColumnType("int");

                    b.Property<int>("Yellow_Cards")
                        .HasColumnType("int");

                    b.Property<int>("Yellow_Other")
                        .HasColumnType("int");

                    b.HasKey("Title");

                    b.ToTable("Rubin");
                });

            modelBuilder.Entity("SportStats.Models.Sochi", b =>
                {
                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Guest_Goals")
                        .HasColumnType("int");

                    b.Property<int>("Guest_Win")
                        .HasColumnType("int");

                    b.Property<string>("Head_Coach")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Home_Goals")
                        .HasColumnType("int");

                    b.Property<int>("Home_Win")
                        .HasColumnType("int");

                    b.Property<int>("Red_Cards")
                        .HasColumnType("int");

                    b.Property<string>("Stadium")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YellowDisruptionOfTheAttack")
                        .HasColumnType("int");

                    b.Property<int>("YellowRoughPlay")
                        .HasColumnType("int");

                    b.Property<int>("YellowUnsportsmanlikeBehavior")
                        .HasColumnType("int");

                    b.Property<int>("Yellow_Cards")
                        .HasColumnType("int");

                    b.Property<int>("Yellow_Other")
                        .HasColumnType("int");

                    b.HasKey("Title");

                    b.ToTable("Sochi");
                });

            modelBuilder.Entity("SportStats.Models.Spartak", b =>
                {
                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Guest_Goals")
                        .HasColumnType("int");

                    b.Property<int>("Guest_Win")
                        .HasColumnType("int");

                    b.Property<string>("Head_Coach")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Home_Goals")
                        .HasColumnType("int");

                    b.Property<int>("Home_Win")
                        .HasColumnType("int");

                    b.Property<int>("Red_Cards")
                        .HasColumnType("int");

                    b.Property<string>("Stadium")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YellowDisruptionOfTheAttack")
                        .HasColumnType("int");

                    b.Property<int>("YellowRoughPlay")
                        .HasColumnType("int");

                    b.Property<int>("YellowUnsportsmanlikeBehavior")
                        .HasColumnType("int");

                    b.Property<int>("Yellow_Cards")
                        .HasColumnType("int");

                    b.Property<int>("Yellow_Other")
                        .HasColumnType("int");

                    b.HasKey("Title");

                    b.ToTable("Spartak");
                });

            modelBuilder.Entity("SportStats.Models.Ufa", b =>
                {
                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Guest_Goals")
                        .HasColumnType("int");

                    b.Property<int>("Guest_Win")
                        .HasColumnType("int");

                    b.Property<string>("Head_Coach")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Home_Goals")
                        .HasColumnType("int");

                    b.Property<int>("Home_Win")
                        .HasColumnType("int");

                    b.Property<int>("Red_Cards")
                        .HasColumnType("int");

                    b.Property<string>("Stadium")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YellowDisruptionOfTheAttack")
                        .HasColumnType("int");

                    b.Property<int>("YellowRoughPlay")
                        .HasColumnType("int");

                    b.Property<int>("YellowUnsportsmanlikeBehavior")
                        .HasColumnType("int");

                    b.Property<int>("Yellow_Cards")
                        .HasColumnType("int");

                    b.Property<int>("Yellow_Other")
                        .HasColumnType("int");

                    b.HasKey("Title");

                    b.ToTable("Ufa");
                });

            modelBuilder.Entity("SportStats.Models.Ural", b =>
                {
                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Guest_Goals")
                        .HasColumnType("int");

                    b.Property<int>("Guest_Win")
                        .HasColumnType("int");

                    b.Property<string>("Head_Coach")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Home_Goals")
                        .HasColumnType("int");

                    b.Property<int>("Home_Win")
                        .HasColumnType("int");

                    b.Property<int>("Red_Cards")
                        .HasColumnType("int");

                    b.Property<string>("Stadium")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YellowDisruptionOfTheAttack")
                        .HasColumnType("int");

                    b.Property<int>("YellowRoughPlay")
                        .HasColumnType("int");

                    b.Property<int>("YellowUnsportsmanlikeBehavior")
                        .HasColumnType("int");

                    b.Property<int>("Yellow_Cards")
                        .HasColumnType("int");

                    b.Property<int>("Yellow_Other")
                        .HasColumnType("int");

                    b.HasKey("Title");

                    b.ToTable("Ural");
                });

            modelBuilder.Entity("SportStats.Models.Zenit", b =>
                {
                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Guest_Goals")
                        .HasColumnType("int");

                    b.Property<int>("Guest_Win")
                        .HasColumnType("int");

                    b.Property<string>("Head_Coach")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Home_Goals")
                        .HasColumnType("int");

                    b.Property<int>("Home_Win")
                        .HasColumnType("int");

                    b.Property<int>("Red_Cards")
                        .HasColumnType("int");

                    b.Property<string>("Stadium")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YellowDisruptionOfTheAttack")
                        .HasColumnType("int");

                    b.Property<int>("YellowRoughPlay")
                        .HasColumnType("int");

                    b.Property<int>("YellowUnsportsmanlikeBehavior")
                        .HasColumnType("int");

                    b.Property<int>("Yellow_Cards")
                        .HasColumnType("int");

                    b.Property<int>("Yellow_Other")
                        .HasColumnType("int");

                    b.HasKey("Title");

                    b.ToTable("Zenit");
                });
#pragma warning restore 612, 618
        }
    }
}
