// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportStats.Data;

#nullable disable

namespace SportStats.Migrations
{
    [DbContext(typeof(SportStatsContext))]
    [Migration("20220605212515_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SportStats.Models.Zenit", b =>
                {
                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Guest_Goals")
                        .HasColumnType("int");

                    b.Property<int>("Guest_Win")
                        .HasColumnType("int");

                    b.Property<string>("Head_Coach")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Home_Goals")
                        .HasColumnType("int");

                    b.Property<int>("Home_Win")
                        .HasColumnType("int");

                    b.Property<int>("Red_Cards")
                        .HasColumnType("int");

                    b.Property<string>("Stadium")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YellowDisruptionOfTheAttack")
                        .HasColumnType("int");

                    b.Property<int>("YellowRoughPlay")
                        .HasColumnType("int");

                    b.Property<int>("YellowUnsportsmanlikeBehavior")
                        .HasColumnType("int");

                    b.Property<int>("Yellow_Cards")
                        .HasColumnType("int");

                    b.Property<int>("Yellow_Other")
                        .HasColumnType("int");

                    b.HasKey("Title");

                    b.ToTable("Zenit");
                });
#pragma warning restore 612, 618
        }
    }
}
